#!/bin/bash
#
#	/etc/rc.d/init.d/inetd
#
# Starts the inet daemon
#
# chkconfig: 345 44 56
# description: Listen and dispatch ACPI events from the kernel
# processname: inetd

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/sbin/inetd ] || exit 0

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/inetd ]; then
	    echo -n $"Starting inet daemon: "
	    daemon /usr/sbin/inetd 
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/inetd
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping inet daemon: "
	killall /usr/sbin/inetd
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/inetd
	echo
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP inetd
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/inetd ]; then
	    restart
	fi
	;;
status)
	status inetd
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
