#!/bin/bash
#
# Starts the container 
#

# Source function library.
. /etc/rc.d/init.d/functions
. /domain/etc/init/setupfunctions

ctname=`basename $0|cut -d. -f2`
bindnic=`basename $0|cut -d. -f3`
if [ ! -z "$bindnic" ];then
	cname=$ctname${bindnic#eth}
else
	cname=$ctname
fi

[ ! -d /domain/etc/container/config/$ctname ] && exit 0
[ ! -z "$bindnic" -a -z "`grep $bindnic: /proc/net/dev`" ] && exit 0
mkdir /var/lock/container -p
mkdir /var/run/container -p
RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/container/$cname ]; then
	    [ -x /domain/etc/contianer/config/$ctname/hooks/create.before ] && /domain/etc/container/config/$ctname/hooks/create.before $ctname $cname $bindnic
	    echo -n $"Starting $cname daemon: "
	    create-container $ctname $cname $bindnic
	    RETVAL=$?
	    [ $RETVAL -ne 0 ] && return $RETVAL
	    mv /var/run/container/$cname.log /var/run/container/$cname.old.log 2>/dev/null
	    [ -x /domain/etc/contianer/config/$ctname/hooks/create.after ] && /domain/etc/container/config/$ctname/hooks/create.after $ctname $cname $bindnic
	    rm /domain/rootfs/$cname/dev/ctout 2>/dev/null
	    rm /domain/rootfs/$cname/dev/ctin 2>/dev/null
	    mkfifo /domain/rootfs/$cname/dev/ctout
	    mkfifo /domain/rootfs/$cname/dev/ctin
	    /domain/sbin/mon-node $cname /domain/rootfs/$cname/dev/ctout $0 >/dev/null 2>/dev/null &
	    screen -dmS init-$cname  lxc-start -n $cname -l DEBUG -o /var/run/container/$cname.log && success || failure
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/container/$cname
	    [ $RETVAL -eq 0 ] && make-visible $cname
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping $cname daemon: "
	[ -x /domain/etc/contianer/config/$ctname/hooks/stop.before ] && /domain/etc/container/config/$ctname/hooks/stop.before $ctname $cname $bindnic
	lxc-stop -n $cname && success || failure
    	[ -x /domain/etc/contianer/config/$ctname/hooks/stop.before ] && /domain/etc/container/config/$ctname/hooks/stop.before $ctname $cname $bindnic
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/container/$cname
	[ $RETVAL -eq 0 ] && make-invisible $cname
	echo
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	restart
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
clear)
	[ -x /domain/etc/contianer/config/$ctname/hooks/destroy.before ] && /domain/etc/container/config/$ctname/hooks/destroy.before $ctname $cname $bindnic
	destroy-container $cname
	;;
reconfig)
	[ -x /domain/etc/contianer/config/$ctname/hooks/destroy.before ] && /domain/etc/container/config/$ctname/hooks/destroy.before $ctname $cname $bindnic
	destroy-container $cname
	start
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/container/$cname ]; then
	    restart
	fi
	;;
status)
	lxc-info -n $cname
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|reconfig|clean}"
	exit 1
esac

exit $RETVAL
