#!/bin/bash
#
#	/etc/rc.d/init.d/httpd
#
# Starts the http daemon
#
# chkconfig: 345 44 56
# description: Listen and dispatch ACPI events from the kernel
# processname: httpd

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/sbin/httpd ] || exit 0

mkdir -p /etc/www/
RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/httpd ]; then
	    echo -n $"Starting http daemon: "
	    daemon /usr/sbin/httpd -h /etc/www -c /etc/http.conf
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/httpd
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping http daemon: "
	killproc /usr/sbin/httpd
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/httpd
	echo
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP httpd
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/httpd ]; then
	    restart
	fi
	;;
status)
	status httpd
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
