#!/bin/bash
[ "$1" = "eth999" ] && exit
if [ ! -z "`echo $1|grep 'eth.*:0'`" ];then
	prog=`ps|grep "^ *$PPID "`
	logger "publicip change(ifconfig ${*}) by $prog"
fi
/etc/ifconfig $*
#net dev exist?
[ $# -gt 1 ] && /sbin/updateip 
