#!/bin/bash
#prepare keys
found=
checkrootsig(){
	dd if=/dev/$1 bs=1k skip=16 count=16 2>/dev/null|gpg -r XOSTE >/tmp/.rootsig 2>/dev/null
	[ $? -ne 0 ] && return 1	
	mv /tmp/.rootsig /etc/rootsig
	return 0
}

for blockdev in `ls /sys/block/|grep '^hd\|^sd\|^cciss'`
do
	echo -n "Check $blockdev ... "
	checkrootsig $blockdev
	[ $? -ne 0 ] && echo " Not Found" && continue
	echo " Found!" && found=$blockdev && break
done
if [ -z "$found" -a "$1" != "nowait" ];then
	read -t 30 -p "Root Disk Not Found! Press Enter to continue ..."
	exit 1
fi
echo "$found" >/etc/rootdisk
echo
