#!/bin/bash

waitmsg(){
	read -p "$1 Press Enter to continue ..." in
}

waitconfirm(){
	read -p "$1" in
	echo $in
}

waitinput(){
	read -p "$1" in
	[ -n "$in" ] && echo "$in" && return 0
	[ -z "$2" ] && echo "no-default!" && return 1
	echo "$2"
	return 1
}
