#!/bin/bash
[ $# -lt 1 ] && echo "need cpiofile" && exit 1
cd initramfs
[ $? -ne 0 ] && echo "need dir initramfs" && exit 1
cpio --no-absolute-filenames -ui <../${1} 2>&1|tee /tmp/trace|grep file
exit ${PIPESTATUS[0]}
