#!/bin/bash
[ $# -lt 1 ] && echo "need cpiofile" && exit 1
cd initramfs
[ $? -ne 0 ] && echo "need dir initramfs" && exit 1
cpio --no-absolute-filenames -dui <../${1} 2>&1|tee /tmp/trace|grep file
ret=${PIPESTATUS[0]}
[ $ret -eq 2 ] && exit 0 || exit $ret
