#!/bin/bash
for dir in `ls ..`
do
	[ -L ../$dir ] && continue
	[ ! -d ../$dir ] && continue
	[ ! -d ../$dir/customized ] && continue
	grep $1 ../$dir/customized/* 2>/dev/null
	grep $1 ../$dir/meta/* 2>/dev/null
done
