#!/bin/bash
#todo:
#refresh, build-from-source files? when includes, src things should be igonred
[ -z "$1" ] && pkg=`basename $PWD` || pkg=$1
[ -z "$1" ] && dir=$PWD || dir=`dirname $PWD`"$1"
[ -z "$1" ] && out=all || out=$1.all
basever=`cat ../version.base`
if [ -z "$1" ];then
	rm ./initramfs/* -rf
	rm ./deplibs/* -rf
fi
mkdir initramfs/fakeroot/etc -p
[ -z "$1" -a ! -z "$basever" ] && echo "$basever" >initramfs/fakeroot/etc/version.base
echo "@@ Generating package $pkg file list ..." >&2
set -x
./tools/genlistall.sh $1|sed "s/\/\//\//"> list.$out
[ ${PIPESTATUS} -ne 0 ] && exit 1
./tools/gen_init_cpio list.$out >$out.cpio 
[ $? -ne 0 ] && ( echo "gen_init_cpio list.$out fail!" >&2 ) && exit 1
echo "@@ Checking package $pkg cpio ..." >&2
./tools/checkcpio $out.cpio >&2
[ $? -ne 0 ] && exit 1
set +x
[ ! -z "$1" ] && ( echo "@@ Generate $pkg done" >&2 ) && exit 0
#finanal round
echo "@@ Check package $pkg lib depdence ..." >&2
./tools/checkdep initramfs/fakeroot >&2
[ $? -ne 0 ] && exit 1
./tools/checkdep initramfs/fakeroot >&2
[ $? -ne 0 ] && exit 1
./tools/checkdep initramfs/ >&2
[ $? -ne 0 ] && exit 1
./tools/checkdep initramfs/ >&2
[ $? -ne 0 ] && exit 1
echo "@@ Appending package $pkg lib list ..." >&2
./tools/getdir $PWD/deplibs/ |tee list.libs >> list.$out
./tools/gen_init_cpio list.libs >libs.cpio
[ $? -ne 0 ] && ( echo "gen_init_cpio list.libs fail!" >&2 ) && exit 1
chroot $PWD/initramfs/ ldconfig >&2
[ -z $1 ] && echo "$pkg" >initramfs/rootpkg
./tools/getdir $PWD/initramfs/ > list.real.$out
echo "@@ Generate final $pkg cpio archive ..." >&2
./tools/gen_init_cpio list.real.$out >$out.cpio
[ $? -ne 0 ] && ( echo "gen_init_cpio list.real.$out fail!" >&2 ) && exit 1
echo "@@ Done! @@"
exit 0
