#!/bin/bash
[ -z $1 ] && echo "need reference package dir name" && exit 1
[ ! -d $1 ] && echo "reference dir not exist" && exit 1
pkg=`basename $PWD`
basepkg=`basename $1`
echo $basepkg >base
export BASEPKG=$basepkg
./tools/clean
./tools/genall
./tools/packlibs $1
echo "@@ Make package $pkg ..."
mv all.base-$basepkg.cpio $pkg.cpio
echo "size of $pkg.cpio"
du -m $pkg.cpio
gzip -9 $pkg.cpio
touch base-$basepkg
[ ! -f version ] && date -Imin >version
./tools/signpackage $pkg.cpio.gz
