#!/bin/bash
#note! using full path!
prog=`basename $0|sed 's/^get//g'`
[ -z ${1} ] && mydir="$PWD/$prog/" || mydir=$1
getfileloc()
{
	file=${1}
	search=${mydir}
	file=${file/$search//}	
	echo $file
}
for file in `find $mydir|grep -v "$mydir$"`
do
	lfile=`getfileloc $file`
	[ ! -z $2 ] && [ -f $2 ] && [ ! -z `grep $lfile $2` ] && continue
	if [ -L $file ];then
		target=`ls -ld $file|awk '{print $11}'`
		target=`getfileloc $target`
		[ -e $file ] && ofile=$file || ofile=`getfileloc $file`
		[ -e $ofile ] && echo slink `getfileloc $file`" "$target" "`./tools/fmode $ofile|awk '{print $1" "$2" "$3}'` || echo slink `getfileloc $file`" "$target" 0755 1 0"
	elif [ -d $file ];then
		echo dir `getfileloc $file`" "`./tools/fmode $file|awk '{print $1" "$2" "$3}'`	
	elif [ -c $file ];then
		echo nod `getfileloc $file`" "`./tools/fmode $file|awk '{print $1" "$2" "$3}'` c `ls -ld $file|sed 's/,/ /g'|awk '{print $5" "$6}'`	
	elif [ -b $file ];then
		echo nod `getfileloc $file`" "`./tools/fmode $file|awk '{print $1" "$2" "$3}'` b `ls -ld $file|sed 's/,/ /g'|awk '{print $5" "$6}'`	
	elif [ -p $file ];then
		echo pipe `getfileloc $file`" "`./tools/fmode $file|awk '{print $1" "$2" "$3}'`	
	elif [ -S $file ];then
		echo sock `getfileloc $file`" "`./tools/fmode $file|awk '{print $1" "$2" "$3}'`	
	elif [ -f $file ];then
		echo file `getfileloc $file` $file" "`./tools/fmode $file|awk '{print $1" "$2" "$3}'`	
	fi
done
