#!/bin/bash
[ -d boot-cd ] && cdcfg=$PWD/boot-cd || cdcfg=$PWD/../demo-cd/boot-cd

sign=/lib/modules/`uname -r`/build/usr/sign_initramfs_file
ver=`$sign 2>&1|grep ver|awk '{print $5}'|sed s'/)$//g'|sed 's/^0x//g'`
[ ! -d $cdcfg ] && echo "dir boot-cd not exist!" && exit 1
[ ! -f bzImage ] && echo "bzImage not exist!" && exit 1

./tools/makepkgs

touch $cdcfg/packages/pkg.zzpack
#./tools/checksign $cdcfg/demo.sig 2>/dev/null >demo.sig.old
mv demo.sig demo.sig.old
cat demo.sig.old|sed "s/^rootver=.*/rootver=$ver/" >demo.sig
./tools/makesign demo.sig >$cdcfg/demo.sig
rm demo.sig.old

pkg=`basename $PWD`
cp bzImage $cdcfg/isolinux/vmlinuz
echo $ver >$cdcfg/ver
echo $pkg >$cdcfg/pkg
name="$pkg"-`cat ../version.base`."$ver"
mkisofs -r -o $name.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table $cdcfg 
echo "$name.iso has been maden."
mv $name.iso /mnt/hgfs/vmshare/recovery-cd/$name.iso

tftproot=/tftproot
umount $tftproot/boot
mount -o loop /mnt/hgfs/vmshare/recovery-cd/$name.iso $tftproot/boot
